/** Map view type → Pydantic content class name from chuk-view-schemas */
export const CONTENT_CLASS: Record<string, string> = {
  alert: "AlertContent",
  annotation: "AnnotationContent",
  audio: "AudioContent",
  boxplot: "BoxplotContent",
  calendar: "CalendarContent",
  carousel: "CarouselContent",
  chart: "ChartContent",
  chat: "ChatContent",
  code: "CodeContent",
  compare: "CompareContent",
  confirm: "ConfirmContent",
  counter: "CounterContent",
  crosstab: "CrosstabContent",
  dashboard: "DashboardContent",
  datatable: "DataTableContent",
  detail: "DetailContent",
  diff: "DiffContent",
  embed: "EmbedContent",
  filter: "FilterContent",
  flowchart: "FlowchartContent",
  font: "FontContent",
  form: "FormContent",
  funnel: "FunnelContent",
  gallery: "GalleryContent",
  gantt: "GanttContent",
  gauge: "GaugeContent",
  geostory: "GeostoryContent",
  "gis-legend": "GisLegendContent",
  globe: "GlobeContent",
  graph: "GraphContent",
  heatmap: "HeatmapContent",
  image: "ImageContent",
  investigation: "InvestigationContent",
  json: "JsonContent",
  kanban: "KanbanContent",
  layers: "LayersContent",
  log: "LogContent",
  map: "MapContent",
  markdown: "MarkdownContent",
  minimap: "MinimapContent",
  neural: "NeuralContent",
  notebook: "NotebookContent",
  pdf: "PdfContent",
  pivot: "PivotContent",
  poll: "PollContent",
  profile: "ProfileContent",
  progress: "ProgressContent",
  quiz: "QuizContent",
  ranked: "RankedContent",
  sankey: "SankeyContent",
  scatter: "ScatterContent",
  settings: "SettingsContent",
  slides: "SlidesContent",
  spectrogram: "SpectrogramContent",
  split: "SplitContent",
  status: "StatusContent",
  stepper: "StepperContent",
  sunburst: "SunburstContent",
  swimlane: "SwimlaneContent",
  tabs: "TabsContent",
  terminal: "TerminalContent",
  threed: "ThreeDContent",
  timeline: "TimelineContent",
  timeseries: "TimeseriesContent",
  tree: "TreeContent",
  treemap: "TreemapContent",
  video: "VideoContent",
};

/** Map view type → decorator function name (e.g. "chart" → "chart_tool") */
export function decoratorName(viewName: string): string {
  return `${viewName.replace(/-/g, "_")}_tool`;
}

/** Map view type → tool function name (e.g. "chart" → "show_chart") */
export function toolFuncName(viewName: string): string {
  return `show_${viewName.replace(/-/g, "_")}`;
}
