import type { Meta, StoryObj } from "@storybook/react";
import { AnnotationRenderer } from "./App";
import type { AnnotationContent } from "./schema";

const meta = {
  title: "Views/Annotation",
  component: AnnotationRenderer,
  tags: ["autodocs"],
  parameters: { layout: "fullscreen" },
  decorators: [(Story) => <div style={{ height: "600px" }}><Story /></div>],
} satisfies Meta<typeof AnnotationRenderer>;

export default meta;
type Story = StoryObj<typeof meta>;

export const MedicalScan: Story = {
  args: {
    data: {
      type: "annotation",
      version: "1.0",
      title: "Chest X-Ray Analysis",
      imageUrl: "https://picsum.photos/seed/medical/800/600",
      imageWidth: 800,
      imageHeight: 600,
      annotations: [
        {
          kind: "circle",
          id: "region-1",
          cx: 320,
          cy: 280,
          r: 45,
          color: "#ef4444",
          label: "Opacity - Left Upper Lobe",
          strokeWidth: 2,
        },
        {
          kind: "circle",
          id: "region-2",
          cx: 520,
          cy: 320,
          r: 35,
          color: "#f59e0b",
          label: "Calcification",
          strokeWidth: 2,
        },
        {
          kind: "rect",
          id: "area-1",
          x: 200,
          y: 380,
          width: 180,
          height: 120,
          color: "#3b82f6",
          label: "Costophrenic Angle",
          strokeWidth: 2,
        },
        {
          kind: "text",
          id: "label-1",
          x: 30,
          y: 30,
          text: "PA View - Upright",
          color: "#e2e8f0",
          fontSize: 16,
        },
        {
          kind: "text",
          id: "label-2",
          x: 30,
          y: 560,
          text: "R",
          color: "#e2e8f0",
          fontSize: 24,
        },
      ],
    } satisfies AnnotationContent,
  },
};

export const ArchitecturalPlan: Story = {
  args: {
    data: {
      type: "annotation",
      version: "1.0",
      title: "Floor Plan Review",
      imageUrl: "https://picsum.photos/seed/blueprint/900/600",
      imageWidth: 900,
      imageHeight: 600,
      annotations: [
        {
          kind: "rect",
          id: "room-1",
          x: 50,
          y: 50,
          width: 250,
          height: 200,
          color: "#3b82f6",
          label: "Living Room (32 sqm)",
          strokeWidth: 2,
        },
        {
          kind: "rect",
          id: "room-2",
          x: 350,
          y: 50,
          width: 200,
          height: 180,
          color: "#10b981",
          label: "Kitchen (18 sqm)",
          strokeWidth: 2,
        },
        {
          kind: "rect",
          id: "room-3",
          x: 600,
          y: 50,
          width: 250,
          height: 250,
          color: "#8b5cf6",
          label: "Master Bedroom (28 sqm)",
          strokeWidth: 2,
        },
        {
          kind: "arrow",
          id: "flow-1",
          x1: 300,
          y1: 150,
          x2: 350,
          y2: 140,
          color: "#f59e0b",
          label: "Open plan connection",
          strokeWidth: 2,
        },
        {
          kind: "arrow",
          id: "flow-2",
          x1: 550,
          y1: 140,
          x2: 600,
          y2: 175,
          color: "#f59e0b",
          label: "Hallway access",
          strokeWidth: 2,
        },
        {
          kind: "text",
          id: "note-1",
          x: 100,
          y: 450,
          text: "All dimensions in meters",
          color: "#94a3b8",
          fontSize: 14,
        },
        {
          kind: "text",
          id: "note-2",
          x: 100,
          y: 480,
          text: "Scale 1:100",
          color: "#94a3b8",
          fontSize: 14,
        },
      ],
    } satisfies AnnotationContent,
  },
};

export const SatelliteImagery: Story = {
  args: {
    data: {
      type: "annotation",
      version: "1.0",
      title: "Site Survey - Region 4B",
      imageUrl: "https://picsum.photos/seed/satellite/800/800",
      imageWidth: 800,
      imageHeight: 800,
      annotations: [
        {
          kind: "circle",
          id: "feature-1",
          cx: 250,
          cy: 300,
          r: 60,
          color: "#ef4444",
          label: "Structure A - Warehouse",
          strokeWidth: 3,
        },
        {
          kind: "circle",
          id: "feature-2",
          cx: 550,
          cy: 450,
          r: 40,
          color: "#f59e0b",
          label: "Water Tower",
          strokeWidth: 2,
        },
        {
          kind: "circle",
          id: "feature-3",
          cx: 400,
          cy: 650,
          r: 50,
          color: "#10b981",
          label: "Vegetation Cluster",
          strokeWidth: 2,
        },
        {
          kind: "arrow",
          id: "route-1",
          x1: 310,
          y1: 300,
          x2: 510,
          y2: 440,
          color: "#3b82f6",
          label: "Access Road",
          strokeWidth: 2,
        },
        {
          kind: "arrow",
          id: "route-2",
          x1: 550,
          y1: 490,
          x2: 420,
          y2: 610,
          color: "#3b82f6",
          label: "Pipeline",
          strokeWidth: 2,
        },
        {
          kind: "text",
          id: "coord-1",
          x: 20,
          y: 20,
          text: "51.5074 N, 0.1278 W",
          color: "#e2e8f0",
          fontSize: 14,
        },
        {
          kind: "text",
          id: "coord-2",
          x: 20,
          y: 45,
          text: "Captured: 2024-11-15 14:32 UTC",
          color: "#94a3b8",
          fontSize: 12,
        },
        {
          kind: "text",
          id: "scale",
          x: 600,
          y: 760,
          text: "100m",
          color: "#e2e8f0",
          fontSize: 16,
        },
      ],
    } satisfies AnnotationContent,
  },
};
