export interface ViewMeta {
  name: string;
  type: string;
  hasCallTool: boolean;
  category: string;
}

export const VIEW_MANIFEST: ViewMeta[] = [
  { name: "alert", type: "alert", hasCallTool: true, category: "interactive" },
  { name: "annotation", type: "annotation", hasCallTool: false, category: "interactive" },
  { name: "audio", type: "audio", hasCallTool: false, category: "media" },
  { name: "boxplot", type: "boxplot", hasCallTool: false, category: "canvas" },
  { name: "calendar", type: "calendar", hasCallTool: false, category: "data" },
  { name: "carousel", type: "carousel", hasCallTool: false, category: "media" },
  { name: "chart", type: "chart", hasCallTool: false, category: "canvas" },
  { name: "chat", type: "chat", hasCallTool: true, category: "interactive" },
  { name: "code", type: "code", hasCallTool: false, category: "text" },
  { name: "compare", type: "compare", hasCallTool: false, category: "compound" },
  { name: "confirm", type: "confirm", hasCallTool: true, category: "interactive" },
  { name: "counter", type: "counter", hasCallTool: false, category: "compound" },
  { name: "crosstab", type: "crosstab", hasCallTool: false, category: "data" },
  { name: "dashboard", type: "dashboard", hasCallTool: false, category: "layout" },
  { name: "datatable", type: "datatable", hasCallTool: true, category: "data" },
  { name: "detail", type: "detail", hasCallTool: true, category: "compound" },
  { name: "diff", type: "diff", hasCallTool: false, category: "text" },
  { name: "embed", type: "embed", hasCallTool: false, category: "media" },
  { name: "filter", type: "filter", hasCallTool: false, category: "interactive" },
  { name: "flowchart", type: "flowchart", hasCallTool: false, category: "visualization" },
  { name: "form", type: "form", hasCallTool: true, category: "interactive" },
  { name: "funnel", type: "funnel", hasCallTool: false, category: "canvas" },
  { name: "gallery", type: "gallery", hasCallTool: true, category: "media" },
  { name: "gantt", type: "gantt", hasCallTool: false, category: "visualization" },
  { name: "gauge", type: "gauge", hasCallTool: false, category: "canvas" },
  { name: "geostory", type: "geostory", hasCallTool: false, category: "compound" },
  { name: "gis-legend", type: "gis-legend", hasCallTool: false, category: "compound" },
  { name: "globe", type: "globe", hasCallTool: false, category: "compound" },
  { name: "graph", type: "graph", hasCallTool: false, category: "visualization" },
  { name: "heatmap", type: "heatmap", hasCallTool: false, category: "canvas" },
  { name: "image", type: "image", hasCallTool: false, category: "media" },
  { name: "investigation", type: "investigation", hasCallTool: false, category: "data" },
  { name: "json", type: "json", hasCallTool: false, category: "text" },
  { name: "kanban", type: "kanban", hasCallTool: true, category: "data" },
  { name: "layers", type: "layers", hasCallTool: false, category: "layout" },
  { name: "log", type: "log", hasCallTool: false, category: "text" },
  { name: "map", type: "map", hasCallTool: false, category: "compound" },
  { name: "markdown", type: "markdown", hasCallTool: false, category: "text" },
  { name: "minimap", type: "minimap", hasCallTool: false, category: "layout" },
  { name: "neural", type: "neural", hasCallTool: false, category: "visualization" },
  { name: "notebook", type: "notebook", hasCallTool: false, category: "text" },
  { name: "pdf", type: "pdf", hasCallTool: false, category: "media" },
  { name: "pivot", type: "pivot", hasCallTool: false, category: "data" },
  { name: "poll", type: "poll", hasCallTool: true, category: "interactive" },
  { name: "profile", type: "profile", hasCallTool: false, category: "compound" },
  { name: "progress", type: "progress", hasCallTool: false, category: "compound" },
  { name: "quiz", type: "quiz", hasCallTool: true, category: "interactive" },
  { name: "ranked", type: "ranked", hasCallTool: true, category: "data" },
  { name: "sankey", type: "sankey", hasCallTool: false, category: "canvas" },
  { name: "scatter", type: "scatter", hasCallTool: false, category: "canvas" },
  { name: "settings", type: "settings", hasCallTool: true, category: "interactive" },
  { name: "slides", type: "slides", hasCallTool: false, category: "layout" },
  { name: "spectrogram", type: "spectrogram", hasCallTool: false, category: "media" },
  { name: "split", type: "split", hasCallTool: false, category: "layout" },
  { name: "status", type: "status", hasCallTool: false, category: "compound" },
  { name: "stepper", type: "stepper", hasCallTool: false, category: "data" },
  { name: "sunburst", type: "sunburst", hasCallTool: false, category: "visualization" },
  { name: "swimlane", type: "swimlane", hasCallTool: false, category: "visualization" },
  { name: "tabs", type: "tabs", hasCallTool: false, category: "layout" },
  { name: "terminal", type: "terminal", hasCallTool: false, category: "text" },
  { name: "threed", type: "threed", hasCallTool: false, category: "compound" },
  { name: "timeline", type: "timeline", hasCallTool: false, category: "data" },
  { name: "timeseries", type: "timeseries", hasCallTool: false, category: "canvas" },
  { name: "tree", type: "tree", hasCallTool: true, category: "data" },
  { name: "treemap", type: "treemap", hasCallTool: false, category: "visualization" },
  { name: "video", type: "video", hasCallTool: false, category: "media" },
  { name: "shader", type: "shader", hasCallTool: false, category: "canvas" },
  { name: "transcript", type: "transcript", hasCallTool: false, category: "text" },
  { name: "wizard", type: "wizard", hasCallTool: true, category: "interactive" },
];
